# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfauto/artifact.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gfauto import common_pb2 as gfauto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gfauto/artifact.proto\x12\x06gfauto\x1a\x13gfauto/common.proto\"\xc4\x01\n\x10\x41rtifactMetadata\x12+\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1d.gfauto.ArtifactMetadata.Data\x12\x14\n\x0c\x64\x65rived_from\x18\x02 \x03(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x1a\\\n\x04\x44\x61ta\x12L\n\x15\x65xtracted_archive_set\x18\x01 \x01(\x0b\x32+.gfauto.ArtifactMetadataExtractedArchiveSetH\x00\x42\x06\n\x04\x64\x61ta\"N\n#ArtifactMetadataExtractedArchiveSet\x12\'\n\x0b\x61rchive_set\x18\x01 \x01(\x0b\x32\x12.gfauto.ArchiveSetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gfauto.artifact_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ARTIFACTMETADATA']._serialized_start=55
  _globals['_ARTIFACTMETADATA']._serialized_end=251
  _globals['_ARTIFACTMETADATA_DATA']._serialized_start=159
  _globals['_ARTIFACTMETADATA_DATA']._serialized_end=251
  _globals['_ARTIFACTMETADATAEXTRACTEDARCHIVESET']._serialized_start=253
  _globals['_ARTIFACTMETADATAEXTRACTEDARCHIVESET']._serialized_end=331
# @@protoc_insertion_point(module_scope)
