# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfauto/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gfauto/common.proto\x12\x06gfauto\"C\n\x06\x42inary\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\"E\n\x07\x41rchive\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x0boutput_file\x18\x02 \x01(\t\x12\x18\n\x10output_directory\x18\x03 \x01(\t\"Q\n\nArchiveSet\x12!\n\x08\x61rchives\x18\x01 \x03(\x0b\x32\x0f.gfauto.Archive\x12 \n\x08\x62inaries\x18\x02 \x03(\x0b\x32\x0e.gfauto.Binaryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gfauto.common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BINARY']._serialized_start=31
  _globals['_BINARY']._serialized_end=98
  _globals['_ARCHIVE']._serialized_start=100
  _globals['_ARCHIVE']._serialized_end=169
  _globals['_ARCHIVESET']._serialized_start=171
  _globals['_ARCHIVESET']._serialized_end=252
# @@protoc_insertion_point(module_scope)
