"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2019 The GraphicsFuzz Project Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import gfauto.common_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class DeviceList(google.protobuf.message.Message):
    """A list of devices. Also includes the |active_device_names|, which are the ones that will be used when fuzzing
    (so this is really more than just a list).
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACTIVE_DEVICE_NAMES_FIELD_NUMBER: builtins.int
    DEVICES_FIELD_NUMBER: builtins.int
    @property
    def active_device_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def devices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Device]: ...
    def __init__(
        self,
        *,
        active_device_names: collections.abc.Iterable[builtins.str] | None = ...,
        devices: collections.abc.Iterable[global___Device] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["active_device_names", b"active_device_names", "devices", b"devices"]) -> None: ...

global___DeviceList = DeviceList

@typing_extensions.final
class Device(google.protobuf.message.Message):
    """A device, such as an Android device or the host machine with its GPU and drivers."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PREPROCESS_FIELD_NUMBER: builtins.int
    SWIFT_SHADER_FIELD_NUMBER: builtins.int
    HOST_FIELD_NUMBER: builtins.int
    ANDROID_FIELD_NUMBER: builtins.int
    SHADER_COMPILER_FIELD_NUMBER: builtins.int
    BINARIES_FIELD_NUMBER: builtins.int
    DEVICE_PROPERTIES_FIELD_NUMBER: builtins.int
    IGNORED_CRASH_SIGNATURES_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def preprocess(self) -> global___DevicePreprocess: ...
    @property
    def swift_shader(self) -> global___DeviceSwiftShader: ...
    @property
    def host(self) -> global___DeviceHost: ...
    @property
    def android(self) -> global___DeviceAndroid: ...
    @property
    def shader_compiler(self) -> global___DeviceShaderCompiler: ...
    @property
    def binaries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[gfauto.common_pb2.Binary]:
        """A device can specify/override some binaries. E.g. you may want several SwiftShader "devices" with different
        versions or configurations of SwiftShader.
        """
    device_properties: builtins.str
    """The Vulkan device properties, most likely obtained by running "amber -d -V"."""
    @property
    def ignored_crash_signatures(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """A list of crash signatures that will be ignored during fuzzing for this device."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        preprocess: global___DevicePreprocess | None = ...,
        swift_shader: global___DeviceSwiftShader | None = ...,
        host: global___DeviceHost | None = ...,
        android: global___DeviceAndroid | None = ...,
        shader_compiler: global___DeviceShaderCompiler | None = ...,
        binaries: collections.abc.Iterable[gfauto.common_pb2.Binary] | None = ...,
        device_properties: builtins.str = ...,
        ignored_crash_signatures: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["android", b"android", "device", b"device", "host", b"host", "preprocess", b"preprocess", "shader_compiler", b"shader_compiler", "swift_shader", b"swift_shader"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["android", b"android", "binaries", b"binaries", "device", b"device", "device_properties", b"device_properties", "host", b"host", "ignored_crash_signatures", b"ignored_crash_signatures", "name", b"name", "preprocess", b"preprocess", "shader_compiler", b"shader_compiler", "swift_shader", b"swift_shader"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["device", b"device"]) -> typing_extensions.Literal["preprocess", "swift_shader", "host", "android", "shader_compiler"] | None: ...

global___Device = Device

@typing_extensions.final
class DeviceSwiftShader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DeviceSwiftShader = DeviceSwiftShader

@typing_extensions.final
class DevicePreprocess(google.protobuf.message.Message):
    """A virtual device that just executes all steps up until the actual graphics hardware or simulator is needed. This
    helps to find bugs in, say, spirv-opt.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DevicePreprocess = DevicePreprocess

@typing_extensions.final
class DeviceHost(google.protobuf.message.Message):
    """The host machine on which we are running gfauto."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CUSTOM_LAUNCHER_FIELD_NUMBER: builtins.int
    @property
    def custom_launcher(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """A custom launcher program that will be used to run Amber. Typically, the launcher program will modify the
        environment and then execute the program that was passed as a command line argument, forwarding all subsequent arguments.
        E.g.
        custom_launcher = ["/data/mesa_intel.sh"]
        gfauto will run: /data/mesa_intel.sh /data/binaries/amber -d -V
        The launcher should modify environment variables and then run: /data/binaries/amber -d -V
        """
    def __init__(
        self,
        *,
        custom_launcher: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["custom_launcher", b"custom_launcher"]) -> None: ...

global___DeviceHost = DeviceHost

@typing_extensions.final
class DeviceAndroid(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIAL_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    BUILD_FINGERPRINT_FIELD_NUMBER: builtins.int
    serial: builtins.str
    model: builtins.str
    build_fingerprint: builtins.str
    def __init__(
        self,
        *,
        serial: builtins.str = ...,
        model: builtins.str = ...,
        build_fingerprint: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["build_fingerprint", b"build_fingerprint", "model", b"model", "serial", b"serial"]) -> None: ...

global___DeviceAndroid = DeviceAndroid

@typing_extensions.final
class DeviceShaderCompiler(google.protobuf.message.Message):
    """A virtual device that just executes an offline shader compiler."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BINARY_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    binary: builtins.str
    @property
    def args(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        binary: builtins.str = ...,
        args: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["args", b"args", "binary", b"binary"]) -> None: ...

global___DeviceShaderCompiler = DeviceShaderCompiler
