# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfauto/device.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gfauto import common_pb2 as gfauto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gfauto/device.proto\x12\x06gfauto\x1a\x13gfauto/common.proto\"J\n\nDeviceList\x12\x1b\n\x13\x61\x63tive_device_names\x18\x01 \x03(\t\x12\x1f\n\x07\x64\x65vices\x18\x02 \x03(\x0b\x32\x0e.gfauto.Device\"\xe9\x02\n\x06\x44\x65vice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\npreprocess\x18\x02 \x01(\x0b\x32\x18.gfauto.DevicePreprocessH\x00\x12\x31\n\x0cswift_shader\x18\x03 \x01(\x0b\x32\x19.gfauto.DeviceSwiftShaderH\x00\x12\"\n\x04host\x18\x04 \x01(\x0b\x32\x12.gfauto.DeviceHostH\x00\x12(\n\x07\x61ndroid\x18\x05 \x01(\x0b\x32\x15.gfauto.DeviceAndroidH\x00\x12\x37\n\x0fshader_compiler\x18\x07 \x01(\x0b\x32\x1c.gfauto.DeviceShaderCompilerH\x00\x12 \n\x08\x62inaries\x18\x06 \x03(\x0b\x32\x0e.gfauto.Binary\x12\x19\n\x11\x64\x65vice_properties\x18\t \x01(\t\x12 \n\x18ignored_crash_signatures\x18\n \x03(\tB\x08\n\x06\x64\x65vice\"\x13\n\x11\x44\x65viceSwiftShader\"\x12\n\x10\x44\x65vicePreprocess\"%\n\nDeviceHost\x12\x17\n\x0f\x63ustom_launcher\x18\x01 \x03(\t\"I\n\rDeviceAndroid\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x19\n\x11\x62uild_fingerprint\x18\x03 \x01(\t\"4\n\x14\x44\x65viceShaderCompiler\x12\x0e\n\x06\x62inary\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gfauto.device_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DEVICELIST']._serialized_start=52
  _globals['_DEVICELIST']._serialized_end=126
  _globals['_DEVICE']._serialized_start=129
  _globals['_DEVICE']._serialized_end=490
  _globals['_DEVICESWIFTSHADER']._serialized_start=492
  _globals['_DEVICESWIFTSHADER']._serialized_end=511
  _globals['_DEVICEPREPROCESS']._serialized_start=513
  _globals['_DEVICEPREPROCESS']._serialized_end=531
  _globals['_DEVICEHOST']._serialized_start=533
  _globals['_DEVICEHOST']._serialized_end=570
  _globals['_DEVICEANDROID']._serialized_start=572
  _globals['_DEVICEANDROID']._serialized_end=645
  _globals['_DEVICESHADERCOMPILER']._serialized_start=647
  _globals['_DEVICESHADERCOMPILER']._serialized_end=699
# @@protoc_insertion_point(module_scope)
