# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfauto/recipe.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gfauto import common_pb2 as gfauto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gfauto/recipe.proto\x12\x06gfauto\x1a\x13gfauto/common.proto\"j\n\x06Recipe\x12V\n download_and_extract_archive_set\x18\x01 \x01(\x0b\x32*.gfauto.RecipeDownloadAndExtractArchiveSetH\x00\x42\x08\n\x06recipe\"M\n\"RecipeDownloadAndExtractArchiveSet\x12\'\n\x0b\x61rchive_set\x18\x01 \x01(\x0b\x32\x12.gfauto.ArchiveSetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gfauto.recipe_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RECIPE']._serialized_start=52
  _globals['_RECIPE']._serialized_end=158
  _globals['_RECIPEDOWNLOADANDEXTRACTARCHIVESET']._serialized_start=160
  _globals['_RECIPEDOWNLOADANDEXTRACTARCHIVESET']._serialized_end=237
# @@protoc_insertion_point(module_scope)
