"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2019 The GraphicsFuzz Project Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import gfauto.common_pb2
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Recipe(google.protobuf.message.Message):
    """An artifact is a directory containing an ArtifactMetadata proto stored in "artifact.json" and/or a Recipe proto
    stored in "recipe.json", plus any other files and directories within. The recipe is executed to produce the files
    that make up the artifact, which must include the "artifact.json" file.
    See artifact.proto.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOWNLOAD_AND_EXTRACT_ARCHIVE_SET_FIELD_NUMBER: builtins.int
    @property
    def download_and_extract_archive_set(self) -> global___RecipeDownloadAndExtractArchiveSet: ...
    def __init__(
        self,
        *,
        download_and_extract_archive_set: global___RecipeDownloadAndExtractArchiveSet | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["download_and_extract_archive_set", b"download_and_extract_archive_set", "recipe", b"recipe"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["download_and_extract_archive_set", b"download_and_extract_archive_set", "recipe", b"recipe"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["recipe", b"recipe"]) -> typing_extensions.Literal["download_and_extract_archive_set"] | None: ...

global___Recipe = Recipe

@typing_extensions.final
class RecipeDownloadAndExtractArchiveSet(google.protobuf.message.Message):
    """Downloads and extracts one or more archives and makes the binaries available."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ARCHIVE_SET_FIELD_NUMBER: builtins.int
    @property
    def archive_set(self) -> gfauto.common_pb2.ArchiveSet: ...
    def __init__(
        self,
        *,
        archive_set: gfauto.common_pb2.ArchiveSet | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["archive_set", b"archive_set"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["archive_set", b"archive_set"]) -> None: ...

global___RecipeDownloadAndExtractArchiveSet = RecipeDownloadAndExtractArchiveSet
