"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2019 The GraphicsFuzz Project Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import gfauto.common_pb2
import gfauto.device_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Settings(google.protobuf.message.Message):
    """A fuzzing session requires a Settings proto stored in "settings.json".
    Default values are defined in settings_util.py.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEVICE_LIST_FIELD_NUMBER: builtins.int
    CUSTOM_BINARIES_FIELD_NUMBER: builtins.int
    MAXIMUM_DUPLICATE_CRASHES_FIELD_NUMBER: builtins.int
    MAXIMUM_FUZZ_FAILURES_FIELD_NUMBER: builtins.int
    REDUCE_TOOL_CRASHES_FIELD_NUMBER: builtins.int
    REDUCE_CRASHES_FIELD_NUMBER: builtins.int
    REDUCE_BAD_IMAGES_FIELD_NUMBER: builtins.int
    LATEST_BINARY_VERSIONS_FIELD_NUMBER: builtins.int
    EXTRA_GRAPHICS_FUZZ_GENERATE_ARGS_FIELD_NUMBER: builtins.int
    EXTRA_GRAPHICS_FUZZ_REDUCE_ARGS_FIELD_NUMBER: builtins.int
    ONLY_REDUCE_SIGNATURE_REGEX_FIELD_NUMBER: builtins.int
    _COMMENT_FIELD_NUMBER: builtins.int
    EXTRA_SPIRV_FUZZ_GENERATE_ARGS_FIELD_NUMBER: builtins.int
    EXTRA_SPIRV_FUZZ_SHRINK_ARGS_FIELD_NUMBER: builtins.int
    EXTRA_SPIRV_REDUCE_ARGS_FIELD_NUMBER: builtins.int
    COMMON_SPIRV_ARGS_FIELD_NUMBER: builtins.int
    LEGACY_GRAPHICS_FUZZ_VULKAN_ARG_FIELD_NUMBER: builtins.int
    SKIP_SEMANTICS_CHANGING_REDUCTION_FIELD_NUMBER: builtins.int
    SPIRV_OPT_JUST_O_FIELD_NUMBER: builtins.int
    KEEP_REDUCTION_WORK_FIELD_NUMBER: builtins.int
    @property
    def device_list(self) -> gfauto.device_pb2.DeviceList:
        """A list of devices, including the list of active devices names that will actually be used in this session."""
    @property
    def custom_binaries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[gfauto.common_pb2.Binary]:
        """A list of custom binary versions; this should rarely be set, but can be used, for example, if you want to override
        the default versions of some binaries for all devices. It is probably more common to specify binaries for certain
        devices.
        """
    maximum_duplicate_crashes: builtins.int
    """Allow at most this many duplicate crashes per device.
    If 0 (the protobuf default value), a different default value will actually be used, as determined by gfauto.
    """
    maximum_fuzz_failures: builtins.int
    """Store at most this many fuzzing failure files."""
    reduce_tool_crashes: builtins.bool
    """Reduce tool crashes. E.g. spirv-opt or glslangValidator crashes. You can disable this if you would rather focus on
    bugs in your actual test device.
    """
    reduce_crashes: builtins.bool
    """Reduce crashes. E.g. shader compilation errors, shader compilation crashes, runtime crashes."""
    reduce_bad_images: builtins.bool
    """Reduce bad images. E.g. your test device renders an incorrect image."""
    @property
    def latest_binary_versions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[gfauto.common_pb2.Binary]:
        """A list of built-in binary versions that will be generated automatically."""
    @property
    def extra_graphics_fuzz_generate_args(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Extra arguments to pass to the GraphicsFuzz generator."""
    @property
    def extra_graphics_fuzz_reduce_args(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Extra arguments to pass to the GraphicsFuzz reducer."""
    only_reduce_signature_regex: builtins.str
    """If non-empty, only reduce a report if the crash signature matches this regular expression."""
    _comment: builtins.str
    """Comment that links to documentation for this proto."""
    @property
    def extra_spirv_fuzz_generate_args(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Extra arguments to pass to spirv-fuzz during fuzzing (i.e. shader generation)."""
    @property
    def extra_spirv_fuzz_shrink_args(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Extra arguments to pass to spirv-fuzz during shrinking."""
    @property
    def extra_spirv_reduce_args(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Extra arguments to pass to spirv-reduce."""
    @property
    def common_spirv_args(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """These arguments will be passed to any tool that accepts common spirv-val arguments. Supported arguments include:
        --scalar-block-layout, --skip-block-layout, etc. Tools include: spirv-val, spirv-opt, spirv-fuzz, and spirv-reduce.
        This field is typically used to relax SPIR-V validation.
        This field is essentially ONLY used for shader fuzzing/generation and then simply written to the test metadata,
        so the test remains self-contained. When running or reducing a test, the field from the test metadata is used.
        """
    legacy_graphics_fuzz_vulkan_arg: builtins.bool
    """If true, pass "--generate-uniform-bindings" to the GraphicsFuzz PrepareReference and Generate tools.
    This is needed for older versions of GraphicsFuzz.
    Otherwise, "--vulkan" is passed.
    """
    skip_semantics_changing_reduction: builtins.bool
    """If true then the semantics changing reduction is skipped.
    We always perform a semantics preserving reduction first, which involves removing transformations from the variant
    shader. If the bug is a crash and this option is false then we continue by performing a semantics changing
    reduction, which involves removing chunks of arbitrary code from the variant shader.
    """
    spirv_opt_just_o: builtins.bool
    """If true, then only use `spirv-opt -O ...` to enhance tests. Once we have a SPIR-V test from a fuzzer, we also
    generate some additional tests by running spirv-opt with `-O`, `-Os`, and three sets of randomly chosen flags, on
    the shaders. The `-O` flag is the best-supported configuration. The other flags may provide limited benefit at the
    cost of having to run 4 extra tests per fuzzed test. Thus, setting |spirv_opt_just_o| to true can save a lot of
    time while still enhancing the fuzzed test.
    """
    keep_reduction_work: builtins.bool
    """If true, then preserve the temporary reduction work directories used when performing a reduction.
    These directories are useful for debugging reduction issues, but are otherwise not very useful and take up
    a lot of space.
    """
    def __init__(
        self,
        *,
        device_list: gfauto.device_pb2.DeviceList | None = ...,
        custom_binaries: collections.abc.Iterable[gfauto.common_pb2.Binary] | None = ...,
        maximum_duplicate_crashes: builtins.int = ...,
        maximum_fuzz_failures: builtins.int = ...,
        reduce_tool_crashes: builtins.bool = ...,
        reduce_crashes: builtins.bool = ...,
        reduce_bad_images: builtins.bool = ...,
        latest_binary_versions: collections.abc.Iterable[gfauto.common_pb2.Binary] | None = ...,
        extra_graphics_fuzz_generate_args: collections.abc.Iterable[builtins.str] | None = ...,
        extra_graphics_fuzz_reduce_args: collections.abc.Iterable[builtins.str] | None = ...,
        only_reduce_signature_regex: builtins.str = ...,
        _comment: builtins.str = ...,
        extra_spirv_fuzz_generate_args: collections.abc.Iterable[builtins.str] | None = ...,
        extra_spirv_fuzz_shrink_args: collections.abc.Iterable[builtins.str] | None = ...,
        extra_spirv_reduce_args: collections.abc.Iterable[builtins.str] | None = ...,
        common_spirv_args: collections.abc.Iterable[builtins.str] | None = ...,
        legacy_graphics_fuzz_vulkan_arg: builtins.bool = ...,
        skip_semantics_changing_reduction: builtins.bool = ...,
        spirv_opt_just_o: builtins.bool = ...,
        keep_reduction_work: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["device_list", b"device_list"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_comment", b"_comment", "common_spirv_args", b"common_spirv_args", "custom_binaries", b"custom_binaries", "device_list", b"device_list", "extra_graphics_fuzz_generate_args", b"extra_graphics_fuzz_generate_args", "extra_graphics_fuzz_reduce_args", b"extra_graphics_fuzz_reduce_args", "extra_spirv_fuzz_generate_args", b"extra_spirv_fuzz_generate_args", "extra_spirv_fuzz_shrink_args", b"extra_spirv_fuzz_shrink_args", "extra_spirv_reduce_args", b"extra_spirv_reduce_args", "keep_reduction_work", b"keep_reduction_work", "latest_binary_versions", b"latest_binary_versions", "legacy_graphics_fuzz_vulkan_arg", b"legacy_graphics_fuzz_vulkan_arg", "maximum_duplicate_crashes", b"maximum_duplicate_crashes", "maximum_fuzz_failures", b"maximum_fuzz_failures", "only_reduce_signature_regex", b"only_reduce_signature_regex", "reduce_bad_images", b"reduce_bad_images", "reduce_crashes", b"reduce_crashes", "reduce_tool_crashes", b"reduce_tool_crashes", "skip_semantics_changing_reduction", b"skip_semantics_changing_reduction", "spirv_opt_just_o", b"spirv_opt_just_o"]) -> None: ...

global___Settings = Settings
